### ISSUE TITLE
Overlay with actual map would be useful also

### ISSUE THREAD

**Issue by sridharb1** [karthi209/chennai-transitmap#1]
Thank you - this is good.

If you could please overlay it on google maps as a layer so that we can specifically see where things are, it would be great. This could be another product, not the same as the classic transit map.

**Comment by karthi209** [comment]
This will have to be a separate project. Transit maps are more tailored to understand the station sequence and how to get within a system rather than geographic accuracy. I'll try to create a separate map using a different method that's geographically accurate.
